---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
 	- name: Copy war to Tomcat
 	  copy:
 	   src: "/var/snap/jenkins/4865/workspace/MavenAnsibleCD/target/MavenAnsible.war"
 	   des: "/opt/tomcat/webapps/MavenAnsible.war"
 	   remote_src: no
 	- name: Restart Tomcat
 	  systemd: 
 	  	name: tomcat
 	  	state: restarted
